#S3
cloud:
  aws:
    credentials:
      accessKey: AKIA3MW7LJZMYVSJJHGJ
      secretKey: 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
    s3:
      bucket: imtellercard
    region:
      static: ap-northeast-2
    stack:
      auto: false

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB